version: '3'

services:
  postgres:
    image: docker.io/postgres:9.6
    restart: always
    volumes:
      - ./init/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./data/guacamole:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: guacamole_db

  guacd:
    image: docker.io/guacamole/guacd:1.1.0
    restart: always
    ports:
      - "4822:4822"
  guacamole:
    image: docker.io/guacamole/guacamole:1.1.0
    restart: always
    ports:
      - "6443:8443"
    hostname: guacamole.adactim.local
    volumes:
      - ./init/guacamole.crt:/usr/local/tomcat/conf/guacamole.crt
      - ./init/guacamole.key:/usr/local/tomcat/conf/guacamole.key
      - ./init/server.xml:/usr/local/tomcat/conf/server.xml
      - ./init/cacerts:/docker-java-home/jre/lib/security/cacerts
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
      GUACD_HOSTNAME: guacd
      GUACAMOLE_HOSTNAME: https://guacamole:8443/guacamole/#
      # https://keycloak.adactim.local:8443/auth/realms/master/.well-known/openid-configuration
      # https://guacamole.apache.org/doc/gug/openid-auth.html
      OPENID_AUTHORIZATION_ENDPOINT: https://keycloak.adactim.local:8443/auth/realms/master/protocol/openid-connect/auth
      OPENID_JWKS_ENDPOINT: https://keycloak.adactim.local:8443/auth/realms/master/protocol/openid-connect/certs
      OPENID_ISSUER: https://keycloak.adactim.local:8443/auth/realms/master
      OPENID_CLIENT_ID: guacamole
      OPENID_REDIRECT_URI: https://guacamole.adactim.local:8443/guacamole/#/settings/sessions
      OPENID_REDIRECT_URI: https://guacamole.adactim.local:8443/guacamole
      OPENID_CLAIM_TYPE: sub
      # OPENID_CLAIM_TYPE: preferred_username
      OPENID_SCOPE: openid profile
      OPENID_ALLOWED_CLOCK_SKEW: 99999
      OPENID_MAX_TOKEN_VALIDITY: 300
      OPENID_MAX_NONCE_VALIDITY: 10
    depends_on:
      - postgres
      - guacd
      - keycloak
  haproxy:
    image: docker.io/haproxy:2.1
    restart: always
    ports:
      - "8443:8443"
    volumes:
        - ./config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - guacamole
      - keycloak
  keycloakpostgres:
    image: docker.io/postgres:9.6
    restart: always
    volumes:
      - ./data/keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
  keycloak:
    image: docker.io/jboss/keycloak:latest
    restart: always
    depends_on:
      - keycloakpostgres
    environment:
      - DB_ADDR=keycloakpostgres
      - DB_DATABASE=keycloak
      - DB_PASSWORD=keycloak
      - DB_SCHEMA=public
      - DB_USER=keycloak
      - DB_VENDOR=POSTGRES
      - KEYCLOAK_LOGLEVEL=INFO
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_USER='admin'
    hostname: keycloak.adactim.local
    ports:
      - "7443:8443"
    tmpfs:
      - /run
      - /tmp
      - /opt/jboss/keycloak/standalone/tmp/vfs/temp
    volumes:
      - ./init/application.keystore:/opt/jboss/keycloak/standalone/configuration/application.keystore
      - ./init/cacerts:/usr/lib/jvm/java-11-openjdk-11.0.6.10-0.el8_1.x86_64/lib/security/cacerts
      - ./config/keycloak/guacamole-client.json:/guacamole-client.json

